apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-jboss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-jboss
  template:
    metadata:
      labels:
        app: hello-jboss
    spec:
      volumes:
        - name: eap-keystore-volume
          secret:
            secretName: eap-ssl-secret
        - name: eap-jgroups-keystore-volume
          secret:
            secretName: eap-jgroup-secret
      containers:
        - name: hello-jboss
          image: hello-jboss
          env:
            - name: OIDC_HOSTNAME_HTTP
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: hostname-http
            - name: OIDC_HOSTNAME_HTTPS
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: hostname-https
            - name: JGROUPS_PING_PROTOCOL
              value: dns.DNS_PING
            - name: OPENSHIFT_DNS_PING_SERVICE_NAME
              value: hello-jboss-ping
            - name: OPENSHIFT_DNS_PING_SERVICE_PORT
              value: "8888"
            - name: HTTPS_KEYSTORE_DIR
              value: /etc/eap-secret-volume
            - name: HTTPS_KEYSTORE
              value: 'eapkeystore.jks'
            - name: HTTPS_KEYSTORE_TYPE
              value: 'JKS'
            - name: HTTPS_NAME
              value: 'https'
            - name: HTTPS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: https-password
            - name: MQ_QUEUES
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: mq-queues
            - name: MQ_TOPICS
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: mq-topics
            - name: JGROUPS_ENCRYPT_PROTOCOL
              value: SYM_ENCRYPT 
            - name: JGROUPS_ENCRYPT_KEYSTORE_DIR
              value: /etc/jgroups-encrypt-secret-volume
            - name: JGROUPS_ENCRYPT_KEYSTORE
              value: 'eapjgroups.jceks'
            - name: JGROUPS_ENCRYPT_NAME
              value: 'jgroups'
            - name: JGROUPS_ENCRYPT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: jgroups-encrypt-password
            - name: JGROUPS_CLUSTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: jgroups-cluster-password
            - name: AUTO_DEPLOY_EXPLODED
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: auto-deploy-exploded
            - name: OIDC_PROVIDER_URL
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: sso-url
            - name: OIDC_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: sso-username
            - name: OIDC_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: sso-password
            - name: OIDC_SECURE_DEPLOYMENT_BEARER_ONLY
              value: "false"
            - name: OIDC_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: sso-client
            - name: OIDC_SECURE_DEPLOYMENT_ENABLE_CORS
              value: "false"
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: sso-secret
            - name: OIDC_DISABLE_SSL_CERTIFICATE_VALIDATION
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: sso-disable-ssl-certificate-validation
            - name: ENABLE_GENERATE_DEFAULT_DATASOURCE
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: enable-generate-default-datasource
            - name: POSTGRESQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: ocp-postgresql-service-host
            - name: POSTGRESQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: ocp-postgresql-service-port
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-name
            - name: POSTGRESQL_DATASOURCE
              value: ocp_postgresql
            - name: MQ_SERVICE_PREFIX_MAPPING
              value: "hello-jboss-amq7=MQ"
            - name: MQ_JNDI
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: mq-jndi
            - name: MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: mq-username
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: mq-password
            - name: MQ_PROTOCOL
              value: "tcp"
            - name: MQ_SERIALIZABLE_PACKAGES
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: mq-serializable-packages
            - name: HELLO_JBOSS_AMQ_TCP_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: amq-service-host
            - name: HELLO_JBOSS_AMQ_TCP_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: amq-service-port
          livenessProbe:
            httpGet:
              path: /health/live
              port: admin
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health/ready
              port: admin
            initialDelaySeconds: 10
          startupProbe:
            httpGet:
              path: /health/live
              port: admin
            initialDelaySeconds: 60
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 8443
              protocol: TCP
              name: https
            - containerPort: 8778
              protocol: TCP
              name: jolokia
            - containerPort: 8888
              protocol: TCP
              name: ping
            - containerPort: 9799
              protocol: TCP
            - containerPort: 9990
              protocol: TCP
              name: admin
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: '1Gi'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: eap-keystore-volume
              mountPath: /etc/eap-secret-volume
              readOnly: true
            - name: eap-jgroups-keystore-volume
              mountPath: /etc/jgroups-encrypt-secret-volume
              readOnly: true
      initContainers:
        - name: hello-jboss-wait-migration
          image: hello-jboss-migration
          env:
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-name
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: ocp-postgresql-service-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: ocp-postgresql-service-port
            - name: FLYWAY_URL
              value: jdbc:postgresql://$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)
            - name: FLYWAY_PARAMS
              value: 'validate'
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
      restartPolicy: Always
      terminationGracePeriodSeconds: 75
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600