apiVersion: batch/v1
kind: Job
metadata:
  name: hello-jboss-migration
  labels:
    app: hello-jboss-migration
spec:
  template:
    metadata:
      labels:
        app: hello-jboss-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: hello-jboss-migration
          image: image-registry.openshift-image-registry.svc:5000/hello-jboss/hello-jboss-migration
          env:
            - name: FLYWAY_PARAMS
              value: 'migrate'
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: hello-jboss
                  key: database-name
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: ocp-postgresql-service-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: hello-jboss
                  key: ocp-postgresql-service-port
            - name: FLYWAY_URL
              value: >-
                jdbc:postgresql://$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)