kind: Secret
apiVersion: v1
metadata:
  name: quarkus-order-logger
data:
  telegram-token: cmVwbGFjZW1l
  telegram-chatid: cmVwbGFjZW1l
  kafka-ssl-truststore-password: cmVwbGFjZW1l
  kafka-ssl-keystore-password: cmVwbGFjZW1l