apiVersion: apps/v1
kind: Deployment
metadata:
  name: commander-cache
spec:
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/commander-cache/commander-cache:latest
        name: commander-cache