apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: quarkus-order-processor-infra
message: This is a template to start infra components.
metadata:
  name: quarkus-order-processor-infra
  annotations:
    description: "quarkus-order-processor-infra template"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: amqbroker
    labels:
      app: amqbroker
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: amqbroker
    template:
      metadata:
        labels:
          app: amqbroker
      spec:
        containers:
          - name: amqbroker
            image: quay.io/gmagnotta/amqbroker:latest
            ports:
              - containerPort: 61616
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8161
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "1024Mi"
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: amqbroker
    labels:
      app: amqbroker
  spec:
    ports:
      - name: 61616-tcp
        protocol: TCP
        port: 61616
        targetPort: 61616
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
      - name: 8161-tcp
        protocol: TCP
        port: 8161
        targetPort: 8161
      - name: 8443-tcp
        protocol: TCP
        port: 8443
        targetPort: 8443
    selector:
      app: amqbroker
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: amqbroker
    labels:
      app: amqbroker
  spec:
    to:
      kind: Service
      name: amqbroker
      weight: 100
    port:
      targetPort: 8161-tcp
    wildcardPolicy: None
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: postgresql
  data:
    postgresql-max-prepared-transactions: '63'
    postgresql-database: 'sample'
- apiVersion: v1
  kind: Secret
  metadata:
    name: postgresql
  data:
    postgresql-username: dXNlckJZWA==
    postgresql-password: VnZReHlJUUwzbmlGUUZlaw==
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: postgresql
    generation: 1
    labels:
      app: postgresql
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: postgresql
    template:
      metadata:
        labels:
          app: postgresql
      spec:
        containers:
          - name: postgresql
            image: registry.redhat.io/rhscl/postgresql-12-rhel7
            ports:
              - containerPort: 5432
                protocol: TCP
            env:
              - name: POSTGRESQL_USER
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: postgresql-username
              - name: POSTGRESQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: postgresql
                    key: postgresql-password
              - name: POSTGRESQL_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: postgresql
                    key: postgresql-database
              - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
                valueFrom:
                  configMapKeyRef:
                    name: postgresql
                    key: postgresql-max-prepared-transactions
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: postgresql
    labels:
      app: postgresql
  spec:
    ports:
      - name: 5432-tcp
        protocol: TCP
        port: 5432
        targetPort: 5432
    selector:
      app: postgresql
    type: ClusterIP
    sessionAffinity: None
parameters: