apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarkus-order-processor-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarkus-order-processor-m2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarkus-order-processor-varlibcontainers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: quarkus-order-processor-pipelineconfig
data:
  dev-image-path: 'image-registry.openshift-image-registry.svc:5000/dev/quarkus-order-processor'
  dev-image-path-migration: 'image-registry.openshift-image-registry.svc:5000/dev/quarkus-order-processor-migration'
  dev-latest-built-image: ''
  dev-latest-built-image-migration: ''
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-order-processor-dev-pipeline
spec:
  params:
    - name: repo-url
  workspaces:
    - name: src
    - name: m2
    - name: varlibcontainers
    - name: empty
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: src
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: compile
      taskRef:
        name: s2i-java-11
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: src
        - name: m2
          workspace: m2
      params:
        - name: CONTEXT
          value: "quarkus-order-processor"
        - name: S2I_SOURCE_DEPLOYMENTS_FILTER
          value: "*-runner.jar lib"
        - name: MAVEN_S2I_GOALS
          value: "package test"
    - name: get-dev-path
      taskRef:
        name: get-configmap-value
      runAfter:
        - compile
      params:
        - name: CONFIGMAP-NAME
          value: "quarkus-order-processor-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-image-path"
    - name: get-dev-path-migration
      taskRef:
        name: get-configmap-value
      runAfter:
        - compile
      params:
        - name: CONFIGMAP-NAME
          value: "quarkus-order-processor-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-image-path-migration"
    - name: build
      taskRef:
        name: image-from-s2i
      runAfter:
        - get-dev-path
      params:
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(tasks.get-dev-path.results.VALUE)
        - name: CONTEXT
          value: "quarkus-order-processor"
      workspaces:
        - name: source
          workspace: src
        - name: varlibcontainers
          workspace: varlibcontainers
    - name: build-migration
      taskRef:
        name: image-from-dockerfile
      runAfter:
        - get-dev-path-migration
      params:
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(tasks.get-dev-path-migration.results.VALUE)
        - name: CONTEXT
          value: "quarkus-order-processor"
        - name: DOCKERFILE
          value: ./Dockerfile.flyway
      workspaces:
        - name: source
          workspace: src
        - name: varlibcontainers
          workspace: varlibcontainers
    - name: deploy
      taskRef:
        name: openshift-actions
      runAfter:
        - build-migration
        - build
      workspaces:
        - name: source
          workspace: src
      params:
        - name: CONTEXT
          value: "quarkus-order-processor"
        - name: SCRIPT
          value: |
            oc process -p IMAGE=$(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST) -p MIGRATION_IMAGE=$(tasks.get-dev-path-migration.results.VALUE)@$(tasks.build-migration.results.IMAGE_DIGEST) -p CAUSE=$(tasks.fetch-repository.results.commit) -f quarkus-order-processor-template.yaml | oc apply -f -
    - name: update-built-image
      taskRef:
        name: set-configmap-value
      runAfter:
        - deploy
      params:
        - name: CONFIGMAP-NAME
          value: "quarkus-order-processor-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image"
        - name: VALUE
          value: $(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST)
    - name: update-built-image-migration
      taskRef:
        name: set-configmap-value
      runAfter:
        - deploy
      params:
        - name: CONFIGMAP-NAME
          value: "quarkus-order-processor-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image-migration"
        - name: VALUE
          value: $(tasks.get-dev-path-migration.results.VALUE)@$(tasks.build-migration.results.IMAGE_DIGEST)