apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarkus-order-processor-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quarkus-order-processor-m2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prepare-deploy
spec:
  params:
    - name: image-path
      type: string
    - name: image-sha
      type: string
    - name: CONTEXT
      type: string
      default: .
    - name: deployment-file
      type: string
      default: deployment.yaml
  workspaces:
    - name: source
  steps:
    - name: replace
      image: registry.access.redhat.com/ubi8/ubi
      workingDir: $(workspaces.source.path)/$(params.CONTEXT)
      script: |
        #!/usr/bin/env bash
        IMAGE="$(params.image-path)@$(params.image-sha)"
        echo "Using image: $IMAGE"
        sed -i "s|{{IMAGE}}|$IMAGE|g" $(params.deployment-file)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mavenbuild
spec:
  params:
    - name: CONTEXT
      type: string
      default: .
    - name: MVN_ARGS
      type: string
      default: "clean package"
  workspaces:
    - name: source
    - name: m2
      mountPath: /home/jboss/.m2/repository
  steps:
    - name: build
      image: registry.access.redhat.com/ubi8/openjdk-11
      workingDir: $(workspaces.source.path)/$(params.CONTEXT)
      script: |
        #!/usr/bin/env bash
        echo "Start maven build"
        mvn -Duser.home=/home/jboss $(params.MVN_ARGS)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubernetes-actions
spec:
  description: >-
    This task is the generic kubectl CLI task which can be used
    to run all kinds of k8s commands
  workspaces:
    - name: manifest-dir
#      optional: true
    - name: kubeconfig-dir
#      optional: true
  results:
    - name: output-result
      description: some result can be emitted if someone wants to.
  params:
    - name: script
      description: The Kubernetes CLI script to run
      type: string
      default: "kubectl $@"
    - name: args
      description: The Kubernetes CLI arguments to run
      type: array
      default:
        - "help"
    - name: image
      default: gcr.io/cloud-builders/kubectl@sha256:8ab94be8b2b4f3d117f02d868b39540fddd225447abf4014f7ba4765cb39f753 #image is huge
      description: Kubectl wrapper image
  steps:
    - name: kubectl
      image: $(params.image)
      workingDir: $(workspaces.manifest-dir.path)
      script: |
        #!/usr/bin/env bash

        if [[ -f $(workspaces.kubeconfig-dir.path)/kubeconfig ]]; then
          export KUBECONFIG=$(workspaces.kubeconfig-dir.path)/kubeconfig
        fi

        $(params.script)

      args:
        - "$(params.args)"
---
# Internal OCP registry is located at image-registry.openshift-image-registry.svc:5000
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-order-processor-pipeline
spec:
  params:
    - name: repo-url
    - name: image-path
    - name: context
  workspaces:
    - name: src
    - name: m2
    - name: empty
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: src
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: compile
      taskRef:
        name: mavenbuild
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: src
        - name: m2
          workspace: m2
      params:
        - name: CONTEXT
          value: $(params.context)
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - compile
      params:
        - name: CONTEXT
          value: $(params.context)
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(params.image-path)
      workspaces:
        - name: source
          workspace: src
    - name: prepare-deploy
      taskRef:
        name: prepare-deploy
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: src
      params:
        - name: image-sha
          value: "$(tasks.build.results.IMAGE_DIGEST)"
        - name: image-path
          value: "$(params.image-path)"
        - name: CONTEXT
          value: $(params.context)
    - name: deploy
      taskRef:
        name: kubernetes-actions
      runAfter:
        - prepare-deploy
      workspaces:
        - name: kubeconfig-dir
          workspace: empty
        - name: manifest-dir
          workspace: src
      params:
        - name: script
          value: |
            kubectl apply -f $(params.context)/deployment.yaml
