apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jboss-eap-test-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jboss-eap-test-artifacts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jboss-eap-test-varlibcontainers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jboss-eap-test-pipelineconfig
data:
  dev-image-path: 'image-registry.openshift-image-registry.svc:5000/dev/jboss-eap-test'
  dev-image-migration-path: 'image-registry.openshift-image-registry.svc:5000/dev/jboss-eap-test-migration'
  release-image-path: 'quay.io/gmagnotta/jboss-eap-test'
  release-image-path-migration: 'quay.io/gmagnotta/jboss-eap-test-migration'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jboss-eap-test-s2ienvironment
data:
  environment: |
    MAVEN_REPOS="nexus"
    NEXUS_MAVEN_REPO_ID="nexus"
    NEXUS_MAVEN_REPO_URL="http://nexus3:8081"
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: eap74-openjdk11-openshift-rhel8
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      description: Red Hat AMQ Broker 7 image
    from:
      kind: DockerImage
      name: registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8
    name: latest
    referencePolicy:
      type: Local
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jboss-eap-test-dev-pipeline
spec:
  params:
    - name: repo-url
  workspaces:
    - name: src
    - name: artifacts
    - name: varlibcontainers
    - name: empty
    - name: s2ienv
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: src
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: get-dev-path
      taskRef:
        name: get-configmap-value
      runAfter:
        - fetch-repository
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-image-path"
    - name: get-migration-path
      taskRef:
        name: get-configmap-value
      runAfter:
        - fetch-repository
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-image-migration-path"
    - name: build
      taskRef:
        name: buildah-s2i
      runAfter:
        - get-dev-path
      workspaces:
        - name: source
          workspace: src
        - name: varlibcontainers
          workspace: varlibcontainers
        - name: artifacts
          workspace: artifacts
        - name: s2ienv
          workspace: s2ienv
      params:
        - name: S2I_IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/dev/eap74-openjdk11-openshift-rhel8"
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(tasks.get-dev-path.results.VALUE)
        - name: CONTEXT
          value: "jboss-eap-test"
        - name: INCREMENTAL
          value: "true"
    - name: build-migrate
      taskRef:
        name: buildah-s2i
      runAfter:
        - get-migration-path
        - build
      workspaces:
        - name: source
          workspace: src
        - name: varlibcontainers
          workspace: varlibcontainers
        - name: artifacts
          workspace: artifacts
        - name: s2ienv
          workspace: s2ienv
      params:
        - name: S2I_IMAGE
          value: "quay.io/gmagnotta/flyway"
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(tasks.get-migration-path.results.VALUE)
        - name: CONTEXT
          value: "jboss-eap-test/src/main/resources/db"
        - name: S2I_SCRIPTS_URL
          value: "/flyway"
    - name: deploy
      taskRef:
        name: openshift-actions
      runAfter:
        - build
        - build-migrate
      workspaces:
        - name: source
          workspace: src
      params:
        - name: CONTEXT
          value: "jboss-eap-test"
        - name: SCRIPT
          value: |
            oc process -p IMAGE=$(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST) -p MIGRATION_IMAGE=$(tasks.get-migration-path.results.VALUE)@$(tasks.build-migrate.results.IMAGE_DIGEST) -p CAUSE=$(tasks.fetch-repository.results.commit) -f jboss-eap-test-template.yaml | oc apply -f -
    - name: migrate
      taskRef:
        name: openshift-actions
      runAfter:
        - build
        - build-migrate
      workspaces:
        - name: source
          workspace: src
      params:
        - name: CONTEXT
          value: "jboss-eap-test"
        - name: SCRIPT
          value: |
            oc process -p MIGRATION_IMAGE=$(tasks.get-migration-path.results.VALUE)@$(tasks.build-migrate.results.IMAGE_DIGEST) -f jboss-eap-test-migration.yaml | oc apply -f -
    - name: update-built-image
      taskRef:
        name: set-configmap-value
      runAfter:
        - deploy
        - migrate
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image"
        - name: VALUE
          value: $(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST)
    - name: update-migrate-image
      taskRef:
        name: set-configmap-value
      runAfter:
        - deploy
        - migrate
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-migration-image"
        - name: VALUE
          value: $(tasks.get-migration-path.results.VALUE)@$(tasks.build-migrate.results.IMAGE_DIGEST)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jboss-eap-test-release-pipeline
spec:
  params:
    - name: image-tag
  workspaces:
    - name: empty
  tasks:
    - name: get-image-built
      taskRef:
        name: get-configmap-value
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image"
    - name: getpushpath
      taskRef:
        name: get-configmap-value
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "release-image-path"
    - name: get-image-built-migration
      taskRef:
        name: get-configmap-value
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-migration-image"
    - name: getpushpath-migration
      taskRef:
        name: get-configmap-value
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "release-image-path-migration"
    - name: copy
      taskRef:
        name: skopeo-copy
        kind: ClusterTask
      runAfter:
        - getpushpath
        - get-image-built
      workspaces:
        - name: images-url
          workspace: empty
      params:
        - name: srcImageURL
          value: "docker://$(tasks.get-image-built.results.VALUE)"
        - name: destImageURL
          value: "docker://$(tasks.getpushpath.results.VALUE):$(params.image-tag)"
        - name: srcTLSverify
          value: "false"
        - name: destTLSverify
          value: "false"
    - name: copy-migration
      taskRef:
        name: skopeo-copy
        kind: ClusterTask
      runAfter:
        - getpushpath-migration
        - get-image-built-migration
      workspaces:
        - name: images-url
          workspace: empty
      params:
        - name: srcImageURL
          value: "docker://$(tasks.get-image-built-migration.results.VALUE)"
        - name: destImageURL
          value: "docker://$(tasks.getpushpath-migration.results.VALUE):$(params.image-tag)"
        - name: srcTLSverify
          value: "false"
        - name: destTLSverify
          value: "false"
