apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: jboss-eap-test
message: This is an OpenShift template to deploy jboss-eap-test.
metadata:
  name: jboss-eap-test
  annotations:
    description: "jboss-eap-test Template"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: jboss-eap-test
  data:
    enable-generate-default-datasource: 'true'
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jboss-eap-test
    labels:
      app: jboss-eap-test
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jboss-eap-test
    template:
      metadata:
        labels:
          app: jboss-eap-test
        annotations:
          kubernetes.io/change-cause: ${CAUSE}
          gitcommit: ${CAUSE}
      spec:
        containers:
          - name: jboss-eap-test
            image: ${IMAGE}
            env:
              - name: ENABLE_GENERATE_DEFAULT_DATASOURCE
                valueFrom:
                  configMapKeyRef:
                    name: jboss-eap-test
                    key: enable-generate-default-datasource
              - name: JGROUPS_PING_PROTOCOL
                value: "dns.DNS_PING"
              - name: OPENSHIFT_DNS_PING_SERVICE_NAME
                value: "jboss-eap-test-ping"
              - name: OPENSHIFT_DNS_PING_SERVICE_PORT
                value: "8888"
              - name: JGROUPS_CLUSTER_PASSWORD
                value: "${JGROUPS_CLUSTER_PASSWORD}"
              - name: AUTO_DEPLOY_EXPLODED
                value: "${AUTO_DEPLOY_EXPLODED}"
              - name: MQ_QUEUES
                value: "${MQ_QUEUES}"
              - name: MQ_TOPICS
                value: "${MQ_TOPICS}"
              - name: MQ_CLUSTER_PASSWORD
                value: "${MQ_CLUSTER_PASSWORD}"
            livenessProbe:
              exec:
                command:
                - "/bin/bash"
                - "-c"
                - "/opt/eap/bin/livenessProbe.sh"
              initialDelaySeconds: 60
            readinessProbe:
              exec:
                command:
                - "/bin/bash"
                - "-c"
                - "/opt/eap/bin/readinessProbe.sh"
              initialDelaySeconds: 10
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8778
                protocol: TCP
              - containerPort: 8888
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "${MEMORY_LIMIT}"
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 75
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: jboss-eap-test
    labels:
      app: jboss-eap-test
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: jboss-eap-test
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Service
  metadata:
    name: jboss-eap-test-ping
    labels:
      app: jboss-eap-test
    annotations:
      service.alpha.kubernetes.io/tolerate-unready-endpoints: true
      description: "The JGroups ping port for clustering"
  spec:
    publishNotReadyAddresses: true
    clusterIP: None
    ports:
      - name: 8888-tcp
        protocol: TCP
        port: 8888
        targetPort: 8888
    selector:
      app: jboss-eap-test
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: jboss-eap-test
    labels:
      app: jboss-eap-test
  spec:
    to:
      kind: Service
      name: jboss-eap-test
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
- description: Container image to use
  name: IMAGE
  required: true
- description: Description of this deployment
  name: CAUSE
- description: Memory Limit
  name: MEMORY_LIMIT
  value: "1Gi"
  required: false
- description: JGroups cluster password
  name: JGROUPS_CLUSTER_PASSWORD
  value: "jgrouppassword"
  required: false
- description: Auto Deploy exploded
  name: AUTO_DEPLOY_EXPLODED
  value: "false"
  required: false
- description: Queue names, separated by commas. These queues will be automatically created when the broker starts. Also, they will be made accessible as JNDI resources in EAP. Note that all queues used by the application *must* be specified here in order to be created automatically on the remote AMQ broker.
  name: MQ_QUEUES
  value: ""
  required: false
- description: Topic names, separated by commas. These topics will be automatically created when the broker starts. Also, they will be made accessible as JNDI resources in EAP. Note that all topics used by the application *must* be specified here in order to be created automatically on the remote AMQ broker.
  name: MQ_TOPICS
  value: ""
  required: false
- description: AMQ cluster admin password
  name: MQ_CLUSTER_PASSWORD
  value: "mqpassword"
  required: false