apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jboss-eap-test-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jboss-eap-test-m2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jboss-eap-test-varlibcontainers-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jboss-eap-test-pipelineconfig
data:
  dev-image-path: 'image-registry.openshift-image-registry.svc:5000/dev/jboss-eap-test'
  release-image-path: 'quay.io/gmagnotta/helloservlet'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jboss-eap-test-s2ienvironment
data:
  environment: |
    LOGGING_SCRIPT_DEBUG="false"
    MAVEN_MIRRORS="nexus"
    NEXUS_MAVEN_MIRROR_ID="nexus"
    NEXUS_MAVEN_MIRROR_OF="*"
    NEXUS_MAVEN_MIRROR_URL="http://nexus3:8081/repository/maven-public/"
    MAVEN_REPOS="nexus"
    NEXUS_MAVEN_REPO_ID="nexus"
    NEXUS_MAVEN_REPO_URL="http://nexus3:8081"
    MAVEN_SETTINGS_XML="/home/jboss/.m2/settings.xml"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jboss-eap-test-dev-pipeline
spec:
  params:
    - name: repo-url
  workspaces:
    - name: src
    - name: m2
    - name: varlibcontainers
    - name: empty
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: src
      params:
        - name: url
          value: $(params.repo-url)
        - name: deleteExisting
          value: "true"
    - name: compile
      taskRef:
        name: s2i-build
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: src
        - name: artifacts
          workspace: m2
      params:
        - name: S2I_IMAGE
          value: "registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8"
        - name: CONTEXT
          value: "jboss-eap-test"
        - name: S2I_ENVIRONMENT
          value: "jboss-eap-test-s2ienvironment"
    - name: get-dev-path
      taskRef:
        name: get-configmap-value
      runAfter:
        - compile
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-image-path"
    - name: build
      taskRef:
        name: image-from-s2i
      runAfter:
        - get-dev-path
      params:
        - name: S2I_IMAGE
          value: "registry.redhat.io/jboss-eap-7/eap74-openjdk11-runtime-openshift-rhel8"
        - name: TLSVERIFY
          value: "false"
        - name: IMAGE
          value: $(tasks.get-dev-path.results.VALUE)
        - name: CONTEXT
          value: "jboss-eap-test"
        - name: S2I_SRC_DIR
          value: "deployments/my-app-1.0-SNAPSHOT.war"
        - name: S2I_DST_DIR
          value: "/deployments/ROOT.war"
      workspaces:
        - name: source
          workspace: src
        - name: varlibcontainers
          workspace: varlibcontainers
    - name: deploy
      taskRef:
        name: openshift-actions
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: src
      params:
        - name: CONTEXT
          value: "jboss-eap-test"
        - name: SCRIPT
          value: |
            oc process -p IMAGE=$(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST) -p CAUSE=$(tasks.fetch-repository.results.commit) -f jboss-eap-test-template.yaml | oc apply -f -
    - name: update-built-image
      taskRef:
        name: set-configmap-value
      runAfter:
        - deploy
      params:
        - name: CONFIGMAP-NAME
          value: "jboss-eap-test-pipelineconfig"
        - name: CONFIGMAP-KEY
          value: "dev-latest-built-image"
        - name: VALUE
          value: $(tasks.get-dev-path.results.VALUE)@$(tasks.build.results.IMAGE_DIGEST)