apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: jboss-eap
  application: ${APPLICATION_NAME}
message: This is an OpenShift template to deploy jboss-eap based applications.
metadata:
  name: jboss-eap
  annotations:
    description: "jboss-eap Template"
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APPLICATION_NAME}
  data:
    database-username: ${DATABASE_USERNAME}
    database-password: ${DATABASE_PASSWORD}
    database-name: ${DATABASE_NAME}
    sso-public-key: ${SSO_PUBLIC_KEY}
    sso-username: ${SSO_USERNAME}
    sso-password: ${SSO_PASSWORD}
    sso-secret: ${SSO_SECRET}
    https-password: ${HTTPS_PASSWORD}
    jgroups-encrypt-password: ${JGROUPS_ENCRYPT_PASSWORD}
    jgroups-cluster-password: ${JGROUPS_CLUSTER_PASSWORD}
    mq-username: ${MQ_USERNAME}
    mq-password: ${MQ_PASSWORD}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${APPLICATION_NAME}
  data:
    enable-generate-default-datasource: ${ENABLE_GENERATE_DEFAULT_DATASOURCE}
    sso-url: ${SSO_URL}
    sso-realm: ${SSO_REALM}
    sso-client: ${SSO_CLIENT}
    sso-disable-ssl-certificate-validation: ${SSO_DISABLE_SSL_CERTIFICATE_VALIDATION}
    hostname-http: ${HOSTNAME_HTTP}
    hostname-https: ${HOSTNAME_HTTPS}
    ocp-postgresql-service-host: ${OCP_POSTGRESQL_SERVICE_HOST}
    ocp-postgresql-service-port: ${OCP_POSTGRESQL_SERVICE_PORT}
    ds1-connection-checker: ${DS1_CONNECTION_CHECKER}
    ds1-driver: ${DS1_DRIVER}
    ds1-exception-sorter: ${DS1_EXCEPTION_SORTER}
    ds1-max-pool-size: ${DS1_MAX_POOL_SIZE}
    ds1-min-pool-size: ${DS1_MIN_POOL_SIZE}
    ds1-nonxa: ${DS1_NONXA}
    ab-prometheus-enable: ${AB_PROMETHEUS_ENABLE}
    auto-deploy-exploded: ${AUTO_DEPLOY_EXPLODED}
    mq-queues: ${MQ_QUEUES}
    mq-topics: ${MQ_TOPICS}
    mq-jndi: ${MQ_JNDI}
    mq-serializable-packages: ${MQ_SERIALIZABLE_PACKAGES}
    amq-service-host: ${AMQ_SERVICE_HOST}
    amq-service-port: ${AMQ_SERVICE_PORT}
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: jboss-eap
  required: true
- description: Defines the username for the datasource
  name: DATABASE_USERNAME
  value: 'amJvc3M='
  required: false
- description: Defines the password for the datasource
  name: DATABASE_PASSWORD
  value: 'amJvc3M='
  required: false
- description: Defines the database name for the datasource
  name: DATABASE_NAME
  value: 'amJvc3M='
  required: false
- description: Red Hat Single Sign-On public key. Public key is recommended to be passed into the template to avoid man-in-the-middle security attacks
  name: SSO_PUBLIC_KEY
  value: ''
  required: false
- description: The username used to access the Red Hat Single Sign-On service. This is used to create the application client(s) within the specified Red Hat Single Sign-On realm
  name: SSO_USERNAME
  value: ''
  required: false
- description: The password for the Red Hat Single Sign-On service user
  name: SSO_PASSWORD
  value: ''
  required: false
- description: The Red Hat Single Sign-On client secret for confidential access
  name: SSO_SECRET
  value: 'cGFzc3dvcmQ='
  required: false
- displayName: Server Keystore Password
  description: The password for the keystore and certificate
  name: HTTPS_PASSWORD
  value: 'cGFzc3dvcmQ='
  required: false
- description: Password used to access the keystore and the certificate, when using SYM_ENCRYPT JGroups cluster traffic encryption protocol. If not set, cluster communication is not encrypted and a warning is issued
  displayName: JGroups Keystore Password
  name: JGROUPS_ENCRYPT_PASSWORD
  value: 'cGFzc3dvcmQ='
  required: false
- description: Password used to authenticate the node so it is allowed to join the JGroups cluster. Required, when using ASYM_ENCRYPT JGroups cluster traffic encryption protocol. If not set, authentication is disabled, cluster communication is not encrypted and a warning is issued. Optional, when using SYM_ENCRYPT JGroups cluster traffic encryption protocol
  name: JGROUPS_CLUSTER_PASSWORD
  value: 'cGFzc3dvcmQ='
  required: false
- displayName: Optional. When included with the value true, the server is provisioned with the default datasource. Otherwise, the default datasource is not included
  description: Enable ExampleDS datasource
  name: ENABLE_GENERATE_DEFAULT_DATASOURCE
  value: 'false'
  required: false
- description: Red Hat Single Sign-On server location
  name: SSO_URL
  value: https://secure-sso/auth
  required: false
- description: Name of the realm to be created in the Red Hat Single Sign-On server if this environment variable is provided
  name: SSO_REALM
  value: demo
  required: false
- description: Client name of this application inside the realm
  name: SSO_CLIENT
  value: jboss-eap
  required: false
- description: Disable certificate validation of SSO Server
  name: SSO_DISABLE_SSL_CERTIFICATE_VALIDATION
  value: 'false'
  required: false
- description: Custom host name for http service route. Leave blank for default host name, e.g. <application-name>.<project>.<default-domain-suffix>
  name: HOSTNAME_HTTP
  value: ''
  required: false
- description: Custom host name for https service route. Leave blank for default host name, e.g. <application-name>.<project>.<default-domain-suffix>
  name: HOSTNAME_HTTPS
  value: ''
  required: false
- description: Defines the database server’s host name or IP address to be used in the datasource’s connection-url property
  name: OCP_POSTGRESQL_SERVICE_HOST
  value: postgresql
  required: false
- description: Defines the database server’s port for the datasource
  name: OCP_POSTGRESQL_SERVICE_PORT
  value: '5432'
  required: false
- description: Specifies a connection checker class that is used to validate connections for the particular database in use
  name: DS1_CONNECTION_CHECKER
  value: org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker
  required: false
- description: Defines Java database driver for the datasource
  name: DS1_DRIVER
  value: postgresql
  required: false
- description: Specifies the exception sorter class that is used to properly detect and clean up after fatal database connection exceptions
  name: DS1_EXCEPTION_SORTER
  value: org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLExceptionSorter
  required: false
- description: Defines the maximum pool size option for the datasource
  name: DS1_MAX_POOL_SIZE
  value: '20'
  required: false
- description: Defines the minimum pool size option for the datasource
  name: DS1_MIN_POOL_SIZE
  value: '20'
  required: false
- description: Defines the datasource as a non-XA datasource
  name: DS1_NONXA
  value: 'true'
  required: false
- description: If set to true, this variable activates the jmx-exporter java agent that exposes Prometheus format metrics
  name: AB_PROMETHEUS_ENABLE
  value: 'true'
  required: false
- description: Controls whether exploded deployment content should be automatically deployed
  name: AUTO_DEPLOY_EXPLODED
  value: 'false'
  required: false
- description: Queue names, separated by commas. These queues will be automatically created when the broker starts. Also, they will be made accessible as JNDI resources in EAP. Note that all queues used by the application *must* be specified here in order to be created automatically on the remote AMQ broker.
  name: MQ_QUEUES
  value: ''
  required: false
- description: Topic names, separated by commas. These topics will be automatically created when the broker starts. Also, they will be made accessible as JNDI resources in EAP. Note that all topics used by the application *must* be specified here in order to be created automatically on the remote AMQ broker.
  name: MQ_TOPICS
  value: ''
  required: false
- description: "JNDI name for connection factory used by applications to connect to the broker, e.g. java:jboss/DefaultJMSConnectionFactory"
  displayName: JMS Connection Factory JNDI Name
  name: MQ_JNDI
  value: 'java:jboss/DefaultJMSConnectionFactory'
  required: false
- displayName: AMQ Username
  description: "User name for standard broker user. It is required for connecting to the broker. If left empty, it will be generated."
  name: MQ_USERNAME
  value: 'dXNlcg=='
  required: true
- displayName: AMQ Password
  description: "Password for standard broker user. It is required for connecting to the broker. If left empty, it will be generated."
  name: MQ_PASSWORD
  value: 'cGFzc3dvcmQ='
  required: true
- displayName: AMQ Serializable Packages
  description: List of packages that are allowed to be serialized for use in ObjectMessage, separated by commas. If your app doesn't use ObjectMessages, leave this blank. This is a security enforcement. For the rationale, see http://activemq.apache.org/objectmessage.html"
  name: MQ_SERIALIZABLE_PACKAGES
  value: ''
  required: false
- description: Defines the amq broker server’s host name or IP address to be used
  name: AMQ_SERVICE_HOST
  value: amqbroker
  required: false
- description: Defines the amq broker server’s port
  name: AMQ_SERVICE_PORT
  value: '61616'
  required: false