apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: jboss-eap-migration
  application: ${APPLICATION_NAME}-migration
message: This is an OpenShift template to deploy jboss-eap-migration to database.
metadata:
  name: jboss-eap-migration
  annotations:
    description: "jboss-eap-migration Template"
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: jboss-eap-test-migrate
    labels:
      app: ${APPLICATION_NAME}-migration
  spec:
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}-migration
      spec:
        restartPolicy: OnFailure
        containers:
          - name: ${APPLICATION_NAME}-migration
            image: ${MIGRATION_IMAGE}
            env:
              - name: FLYWAY_PARAMS
                value: 'migrate'
              - name: FLYWAY_USER
                valueFrom:
                  secretKeyRef:
                    name: ${APPLICATION_NAME}
                    key: database-username
              - name: FLYWAY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: ${APPLICATION_NAME}
                    key: database-password
              - name: DATABASE_NAME
                valueFrom:
                  secretKeyRef:
                    name: ${APPLICATION_NAME}
                    key: database-name
              - name: DATABASE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: ${APPLICATION_NAME}
                    key: ocp-postgresql-service-host
              - name: DATABASE_PORT
                valueFrom:
                  configMapKeyRef:
                    name: jboss-eap
                    key: ocp-postgresql-service-port
              - name: FLYWAY_URL
                value: >-
                  jdbc:postgresql://$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: jboss-eap
  required: true
- description: Container image to use for migration
  name: MIGRATION_IMAGE
  required: true