apiVersion: batch/v1
kind: Job
metadata:
  name: jboss-eap-test-migrate
  labels:
    app: jboss-eap-test
spec:
  template:
    metadata:
      labels:
        app: jboss-eap-test
    spec:
      restartPolicy: OnFailure
      containers:
        - name: jboss-eap-test-migration
          image: <PUT_HERE_IMAGE>
          env:
            - name: FLYWAY_PARAMS
              value: 'migrate'
            - name: FLYWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: <PUT_HERE_VALUE>
                  key: MIGRATION_JDBC
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: <PUT_HERE_VALUE>
                  key: database-username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: <PUT_HERE_VALUE>
                  key: database-password
