apiVersion: batch/v1
kind: Job
metadata:
  name: jboss-eap-test-migrate
  labels:
    app: jboss-eap-test
spec:
  template:
    metadata:
      labels:
        app: jboss-eap-test
    spec:
      restartPolicy: OnFailure
      containers:
        - name: jboss-eap-test-migration
          image: <PUT_HERE_IMAGE>
          env:
            - name: FLYWAY_PARAMS
              value: 'migrate'
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: <PUT_HERE_VALUE>
                  key: database-username
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: <PUT_HERE_VALUE>
                  key: database-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: <PUT_HERE_VALUE>
                  key: database-name
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: <PUT_HERE_VALUE>
                  key: ocp-postgresql-service-host
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: jboss-eap
                  key: ocp-postgresql-service-port
            - name: FLYWAY_URL
              value: >-
                jdbc:postgresql://$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)
