schemaVersion: 2.2.0
metadata:
  name: hello-jboss
  version: 1.0.0
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      mountSources: true
      env:
        - name: KUBEDOCK_ENABLED
          value: "true"
        - name: USE_JAVA17
          value: "true"
        - name: CONTAINER_HOST
          value: "tcp://127.0.0.1:2475"
      volumeMounts:
        - name: deployments
          path: /deployments
        - name: m2
          path: /tmp/m2
      endpoints:
        - exposure: none
          name: kubedock
          protocol: tcp
          targetPort: 2475
        - exposure: public
          name: http-booster
          protocol: http
          targetPort: 8080
          attributes:
            discoverable: true
            urlRewriteSupported: true
        - exposure: internal
          name: debug
          protocol: http
          targetPort: 5005
  - name: jboss-webserver-6
    container:
      image: registry.redhat.io/jboss-webserver-6/jws60-openjdk17-openshift-rhel8
      mountSources: true
      endpoints:
        - name: http
          exposure: public
          targetPort: 8080
          protocol: http
      env:
        - name: AN_ENV_VARIABLE
          value: 'THE_CONTENT'
      volumeMounts:
        - name: deployments
          path: /deployments
  - name: deployments
    volume:
      size: 1Gi
  - name: m2
    volume:
      size: 1Gi
commands:
  - id: compile
    exec:
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: 'mvn -Dmaven.repo.local=/tmp/m2 clean package'
  - id: copyresources
    exec:
      component: tools
      workingDir: ${PROJECT_SOURCE}
      commandLine: 'cp $PROJECT_SOURCE/target/ROOT.war /deployments/'
  - id: compileandcopy
    composite:
      commands:
        - compile
        - copyresources
      parallel: false
      group:
        kind: build
        isDefault: true
  - id: run
    exec:
      component: jboss-webserver-6
      workingDir: ${PROJECT_SOURCE}
      commandLine: '/usr/local/s2i/run'
      group:
        kind: run
        isDefault: true
