apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: hello-tomcat
message: This is an OpenShift template to deploy hello-tomcat.
metadata:
  name: hello-tomcat
  annotations:
    description: "hello-tomcat Template"
objects:
- apiVersion: v1
  data:
    tomcat-users.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!--
        Licensed to the Apache Software Foundation (ASF) under one or more
        contributor license agreements.  See the NOTICE file distributed with
        this work for additional information regarding copyright ownership.
        The ASF licenses this file to You under the Apache License, Version 2.0
        (the "License"); you may not use this file except in compliance with
        the License.  You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.
      -->
      <tomcat-users xmlns="http://tomcat.apache.org/xml"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                    version="1.0">
      <!--
        By default, no user is included in the "manager-gui" role required
        to operate the "/manager/html" web application.  If you wish to use this app,
        you must define such a user - the username and password are arbitrary.

        Built-in Tomcat manager roles:
          - manager-gui    - allows access to the HTML GUI and the status pages
          - manager-script - allows access to the HTTP API and the status pages
          - manager-jmx    - allows access to the JMX proxy and the status pages
          - manager-status - allows access to the status pages only

        The users below are wrapped in a comment and are therefore ignored. If you
        wish to configure one or more of these users for use with the manager web
        application, do not forget to remove the <!.. ..> that surrounds them. You
        will also need to set the passwords to something appropriate.
      -->
      <!--
        <user username="admin" password="<must-be-changed>" roles="manager-gui"/>
        <user username="robot" password="<must-be-changed>" roles="manager-script"/>
      -->
      <!--
        The sample user and role entries below are intended for use with the
        examples web application. They are wrapped in a comment and thus are ignored
        when reading this file. If you wish to configure these users for use with the
        examples web application, do not forget to remove the <!.. ..> that surrounds
        them. You will also need to set the passwords to something appropriate.
      -->
        <role rolename="user"/>
        <user username="tomcat" password="tomcat" roles="user"/>
      <!--
        <role rolename="tomcat"/>
        <role rolename="role1"/>
        <user username="tomcat" password="<must-be-changed>" roles="tomcat"/>
        <user username="both" password="<must-be-changed>" roles="tomcat,role1"/>
        <user username="role1" password="<must-be-changed>" roles="role1"/>
      -->
      </tomcat-users>
  kind: ConfigMap
  metadata:
    name: hello-tomcat
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hello-tomcat
    labels:
      app: hello-tomcat
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: hello-tomcat
    template:
      metadata:
        labels:
          app: hello-tomcat
        annotations:
          kubernetes.io/change-cause: ${CAUSE}
          gitcommit: ${CAUSE}
      spec:
        containers:
          - name: hello-tomcat
            image: ${IMAGE}
            readinessProbe:
              exec:
                command:
                - "/bin/bash"
                - "-c"
                - 'curl --noproxy ''*'' -is ''http://localhost:8080/health'' | grep -iq ''"status": "UP"'''
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8778
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: tomcat-users
              mountPath: /opt/jws-5.6/tomcat/conf/tomcat-users.xml
              subPath: tomcat-users.xml
        restartPolicy: Always
        terminationGracePeriodSeconds: 60
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
        volumes:
          - name: tomcat-users
            configMap:
              name: hello-tomcat
              items:
              - key: tomcat-users.xml
                path: tomcat-users.xml
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: hello-tomcat
    labels:
      app: hello-tomcat
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
      - name: 8778-tcp
        protocol: TCP
        port: 8778
        targetPort: 8778
    selector:
      app: hello-tomcat
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: hello-tomcat
    labels:
      app: hello-tomcat
  spec:
    to:
      kind: Service
      name: hello-tomcat
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
- description: Container image to use
  name: IMAGE
  required: true
- description: Description of this deployment
  name: CAUSE
  required: true