apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: amq-broker-rhel8
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      description: Red Hat AMQ Broker 7 image
    from:
      kind: DockerImage
      name: registry.redhat.io/amq7/amq-broker-rhel8:7.8
    name: latest
    referencePolicy:
      type: Local