apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: datagrid-8-rhel8
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      description: Red Hat Datagrid 8
    from:
      kind: DockerImage
      name: registry.redhat.io/datagrid/datagrid-8-rhel8
    name: latest
    referencePolicy:
      type: Local