apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: minio
message: This is an OpenShift template to deploy minio.
metadata:
  name: minio
  annotations:
    description: "minio Template"
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: minio
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: minio
    labels:
      app: minio
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: minio
    template:
      metadata:
        labels:
          app: minio
      spec:
        volumes:
          - name: minio-data
            persistentVolumeClaim:
              claimName: minio
        containers:
          - name: minio
            image:  quay.io/minio/minio
            args: ["server", "--console-address", ":9001", "/storage"]
            env:
            # Minio access key and secret key
            - name: MINIO_ROOT_USER
              value: "minio"
            - name: MINIO_ROOT_PASSWORD
              value: "minio123"
            ports:
              - containerPort: 9000
                protocol: TCP
              - containerPort: 9001
                protocol: TCP
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: minio-data
                mountPath: /storage
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: minio
    labels:
      app: minio
  spec:
    ports:
      - name: 9000-tcp
        protocol: TCP
        port: 9000
        targetPort: 9000
      - name: 9001-tcp
        protocol: TCP
        port: 9001
        targetPort: 9001
    selector:
      app: minio
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: minio
    labels:
      app: minio
  spec:
    to:
      kind: Service
      name: minio
      weight: 100
    port:
      targetPort: 9001-tcp
    wildcardPolicy: None
parameters:
