#
# Example Nexus3 oss deployment
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    template: nexus3
  name: nexus3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nexus3
    template: nexus3
    app.kubernetes.io/name: nexus3
    app.kubernetes.io/part-of: nexus3
  name: nexus3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nexus3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      containers:
      - image: registry.connect.redhat.com/sonatype/nexus-repository-manager
        imagePullPolicy: IfNotPresent
        name: nexus3
        ports:
        - containerPort: 8081
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus3
    template: nexus3
  name: nexus3
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: nexus3
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: nexus3
    template: nexus3
  name: nexus3
spec:
  port:
    targetPort: 8081-tcp
  to:
    kind: Service
    name: nexus3
    weight: 100
  wildcardPolicy: None
