apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: datagrid
  application: ${APPLICATION_NAME}
message: This is a template to provision datagrid
metadata:
  name: datagrid
  annotations:
    description: "datagrid template"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: datagrid-8-rhel8
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations:
        description: Red Hat Datagrid 8
      from:
        kind: DockerImage
        name: registry.redhat.io/datagrid/datagrid-8-rhel8
      name: latest
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APPLICATION_NAME}
  data:
    user: ${USER}
    password: ${PASSWORD}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${APPLICATION_NAME}
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
        annotations:
          alpha.image.policy.openshift.io/resolve-names: '*'
      spec:
        containers:
          - name: datagrid
            image: datagrid-8-rhel8:latest
            ports:
              - containerPort: 11221
                protocol: TCP
              - containerPort: 11222
                protocol: TCP
              - containerPort: 2157
                protocol: TCP
              - containerPort: 47500
                protocol: TCP
              - containerPort: 57600
                protocol: TCP
              - containerPort: 7800
                protocol: TCP
            env:
              - name: USER
                valueFrom:
                  secretKeyRef:
                    name: ${APPLICATION_NAME}
                    key: user
              - name: PASS
                valueFrom:
                  secretKeyRef:
                    name: ${APPLICATION_NAME}
                    key: password
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "1Gi"
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 60
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    ports:
      - name: 11222-tcp
        protocol: TCP
        port: 11222
        targetPort: 11222
    selector:
      app: ${APPLICATION_NAME}
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPLICATION_NAME}-nodes
    labels:
      app: ${APPLICATION_NAME}-nodes
  spec:
    publishNotReadyAddresses: true
    clusterIP: None
    ports:
      - name: 11222-tcp
        protocol: TCP
        port: 11222
        targetPort: 11222
    selector:
      app: ${APPLICATION_NAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      weight: 100
    port:
      targetPort: 11222-tcp
    wildcardPolicy: None
parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: datagrid
  required: true
- displayName: User account in base64
  description: User name to be created.
  name: USER
  value: 'YWRtaW4='
  required: true
- displayName: Password in base64
  description: Password for the user account.
  name: PASSWORD
  value: 'cGFzc3dvcmQ='
  required: true
