apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: template-prometheus
message: This is a template to provision prometheus.
metadata:
  name: template-prometheus
  annotations:
    description: "prometheus template"
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: prometheus
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: prometheus
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: view
  subjects:
  - kind: ServiceAccount
    name: prometheus
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: prometheus
    labels:
      app: prometheus
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: prometheus
    template:
      metadata:
        labels:
          app: prometheus
      spec:
        containers:
          - name: prometheus
            image: registry.redhat.io/openshift4/ose-prometheus
            ports:
              - containerPort: 9090
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "1024Mi"
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: config-volume
                mountPath: /etc/prometheus/prometheus.yml
                subPath: prometheus.yml
        serviceAccountName: prometheus
        volumes:
          - name: config-volume
            configMap:
              name: prometheus
              items:
              - key: prometheus.yaml
                path: prometheus.yml
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: prometheus
    labels:
      app: prometheus
    annotations:
      prometheus.io/scrape_port: '9090'
      prometheus.io/scrape: 'true'
  spec:
    ports:
      - name: 9090-tcp
        protocol: TCP
        port: 9090
        targetPort: 9090
    selector:
      app: prometheus
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: prometheus
    labels:
      app: prometheus
  spec:
    to:
      kind: Service
      name: prometheus
      weight: 100
    port:
      targetPort: 9090-tcp
    wildcardPolicy: None
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: prometheus
  data:
    prometheus.yaml: |-
      global:
        scrape_interval: 15s
        external_labels:
          monitor: 'codelab-monitor'
      alerting:
        alertmanagers:
          - static_configs:
              - targets:
      scrape_configs:
        - job_name: "kubernetes-service-endpoints"

          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                names:
                  - '${NAMESPACE}'

          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

          relabel_configs:

            # Relabel to scrape only endpoints that have
            # "prometheus.io/scrape = true" annotation.
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
              action: keep
              regex: true
            # Relabel to scrape only single, desired port for the service based
            # on endpoints "prometheus.io/scrape_port = <port>" annotation.
            - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_scrape_port]
              action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              target_label: __address__
            - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
              action: replace
              target_label: __metrics_path__
              regex: (.+)
parameters:
- displayName: Namespace
  description: The name of the namespace to monitor.
  name: NAMESPACE
  required: true
