apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jws56-openjdk11-openshift-rhel8
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      description: Red Hat JBoss WS 5.6 Image
    from:
      kind: DockerImage
      name: registry.redhat.io/jboss-webserver-5/jws56-openjdk11-openshift-rhel8
    name: latest
    referencePolicy:
      type: Local
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hello-tomcat
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hello-tomcat-artifact
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-tomcat-artifact
  labels:
    application: hello-tomcat
spec:
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 512Mi
  source:
    type: Git
    git:
      ref: master
      uri: 'https://github.com/gmagnotta/examples'
    contextDir: hello-tomcat
  strategy:
    type: Source
    sourceStrategy:
      forcePull: true
      incremental: true
      from:
        kind: ImageStreamTag
        name: 'jws56-openjdk11-openshift-rhel8:latest'
      env:
        - name: MAVEN_ARGS_APPEND
          value: '-Dsonar.projectKey=hello-tomcat -Dsonar.projectName=''''hello-tomcat'''' -Dsonar.host.url=http://sonarqube-giuseppe-magnotta-dev.apps.sandbox-m3.1530.p1.openshiftapps.com  -Dsonar.token=sqp_ae716219200c705ff2ff1698f2e2c860573d12aa'
        - name: MAVEN_S2I_GOALS
          value: 'clean package sonar:sonar'
  postCommit: {}
  runPolicy: Serial
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-tomcat-artifact:latest'
  triggers: []
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello-tomcat
  labels:
    application: hello-tomcat
spec:
  resources: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM jws56-openjdk11-openshift-rhel8:latest
      COPY /hello-tomcat.war /deployments/ROOT.war
    images:
    - from:
        kind: ImageStreamTag
        name: 'hello-tomcat-artifact:latest'
      paths:
      - sourcePath: '/deployments/hello-tomcat.war'
        destinationDir: '.'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'jws56-openjdk11-openshift-rhel8:latest'
  postCommit: {}
  runPolicy: Serial
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-tomcat:latest'
  triggers: []
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-tomcat-pipelineconfig
data:
  release-image-path: 'quay.io/gmagnotta/hello-tomcat'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secrets
data:
  hello-tomcat: c3FwX2FlNzE2MjE5MjAwYzcwNWZmMmZmMTY5OGYyZTJjODYwNTczZDEyYWEK
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-tomcat
spec:
  workspaces:
    - name: source
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: "https://github.com/gmagnotta/examples"
        - name: deleteExisting
          value: "true"
    - name: scan-source
      params:
        - name: sonarqubeHostUrl
          value: "http://sonarqube-giuseppe-magnotta-dev.apps.sandbox-m3.1530.p1.openshiftapps.com"
        - name: sonarqubeProjectKey
          value: "hello-tomcat"
        - name: sonarqubeProjectSecretKey
          value: "hello-tomcat"
        - name: sonarqubeProjectSecret
          value: "sonarqube-secrets"
        - name: path
          value: "hello-tomcat"
      runAfter:
        - fetch-source
      taskRef:
        kind: Task
        name: scan-code
      workspaces:
        - name: repository
          workspace: source
    - name: build-artifacts
      taskRef:
        name: s2i-startbuild-cli
      runAfter:
        - scan-source
      params:
        - name: BUILDCONFIG-NAME
          value: "hello-tomcat-artifact"
    - name: build-runtime-image
      taskRef:
        name: s2i-startbuild-cli
      runAfter:
        - build-artifacts
      params:
        - name: BUILDCONFIG-NAME
          value: "hello-tomcat"
    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-runtime-image
      workspaces:
        - name: manifest-dir
          workspace: source
      params:
        - name: SCRIPT
          value: |
            cd hello-tomcat/k8s/overlay/dev

            cat <<EOF > kustomization.yaml
            apiVersion: kustomize.config.k8s.io/v1beta1
            kind: Kustomization

            resources:
            - ../../base
            images:
            - name: hello-tomcat
              newName: $(tasks.build-runtime-image.results.VALUE)
            EOF

            oc apply -k .
    - name: update-built-image
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - build-runtime-image
      params:
        - name: SCRIPT
          value: |
            set -eu -o pipefail

            oc patch configmap/hello-tomcat-pipelineconfig --type merge -p '{"data":{"dev-latest-built-image":"$(tasks.build-runtime-image.results.VALUE)"}}'
    - name: sign-image
      taskRef:
        name: cosign
      runAfter:
        - update-built-image
      params:
        - name: IMAGETOSIGN
          value: $(tasks.build-runtime-image.results.VALUE)
        - name: COSIGNKEY
          value: "k8s://giuseppe-magnotta-dev/signing-secrets"