apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: quarkus-datagrid-api
message: This is an OpenShift template to deploy quarkus-datagrid-api.
metadata:
  name: quarkus-datagrid-api
  annotations:
    description: "quarkus-datagrid-api Template"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: quarkus-datagrid-api
  data:
    quarkus-artemis-url: ${ARTEMIS_URL}
    quarkus-log-level: 'INFO'
    quarkus-log-file-path: '/tmp/quarkus.log'
    quarkus-jaeger-sampler-param: '0'
    quarkus-jaeger-reporter-log-spans: 'false'
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quarkus-datagrid-api
    labels:
      app: quarkus-datagrid-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: quarkus-datagrid-api
    template:
      metadata:
        labels:
          app: quarkus-datagrid-api
        annotations:
          kubernetes.io/change-cause: ${CAUSE}
          gitcommit: ${CAUSE}
      spec:
        volumes:
          - name: camel-quarkus-datagrid-api-1
            emptyDir: {}
        containers:
          - name: quarkus-datagrid-api
            image: ${IMAGE}
            env:
              - name: QUARKUS_ARTEMIS_URL
                valueFrom:
                  configMapKeyRef:
                    name: quarkus-datagrid-api
                    key: quarkus-artemis-url
              - name: QUARKUS_LOG_LEVEL
                valueFrom:
                  configMapKeyRef:
                    name: quarkus-datagrid-api
                    key: quarkus-log-level
              - name: QUARKUS_LOG_FILE_PATH
                valueFrom:
                  configMapKeyRef:
                    name: quarkus-datagrid-api
                    key: quarkus-log-file-path
              - name: QUARKUS_JAEGER_SAMPLER_PARAM
                valueFrom:
                  configMapKeyRef:
                    name: quarkus-datagrid-api
                    key: quarkus-jaeger-sampler-param
              - name: QUARKUS_JAEGER_REPORTER_LOG_SPANS
                valueFrom:
                  configMapKeyRef:
                    name: quarkus-datagrid-api
                    key: quarkus-jaeger-reporter-log-spans
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: camel-quarkus-datagrid-api-1
                mountPath: /opt/quarkus-app/ObjectStore
            livenessProbe:
              httpGet:
                path: /q/health/live
                port: 8080
            readinessProbe:
              httpGet:
                path: /q/health/ready
                port: 8080
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/scrape_port: '8080'
      prometheus.io/path: /q/metrics
    name: quarkus-order-processor-api
    labels:
      app: quarkus-datagrid-api
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: quarkus-datagrid-api
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: quarkus-datagrid-api
    labels:
      app: quarkus-datagrid-api
  spec:
    to:
      kind: Service
      name: quarkus-datagrid-api
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
- description: Artemis url
  name: ARTEMIS_URL
  value: 'tcp://amqbroker:61616'
- description: Container image to use
  name: IMAGE
  required: true
- description: Description of this deployment
  name: CAUSE
  required: true
