apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: quarkus-order-processor-ui
message: This is an OpenShift template to deploy quarkus-order-processor-ui.
metadata:
  name: quarkus-order-processor-ui
  annotations:
    description: "quarkus-order-processor-ui Template"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: quarkus-order-processor-ui
  data:
    backend-url: ${BACKEND_URL}
    quarkus-log-level: 'INFO'
    quarkus-log-file-path: '/tmp/quarkus.log'
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quarkus-order-processor-ui
    labels:
      app: quarkus-order-processor-ui
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: quarkus-order-processor-ui
    template:
      metadata:
        labels:
          app: quarkus-order-processor-ui
        annotations:
          kubernetes.io/change-cause: ${CAUSE}
          gitcommit: ${CAUSE}
      spec:
        containers:
          - name: quarkus-order-processor-ui
            image: ${IMAGE}
            env:
              - name: BACKEND_URL
                valueFrom:
                  configMapKeyRef:
                    name: quarkus-order-processor-ui
                    key: backend-url
              - name: QUARKUS_LOG_LEVEL
                valueFrom:
                  configMapKeyRef:
                    name: quarkus-order-processor-ui
                    key: quarkus-log-level
              - name: QUARKUS_LOG_FILE_PATH
                valueFrom:
                  configMapKeyRef:
                    name: quarkus-order-processor-ui
                    key: quarkus-log-file-path
            readinessProbe:
              exec:
                command:
                - "/bin/bash"
                - "-c"
                - 'curl --noproxy ''*'' -is ''http://localhost:8080/health'' | grep -iq ''"status": "UP"'''
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8778
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 60
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: quarkus-order-processor-ui
    labels:
      app: quarkus-order-processor-ui
  spec:
    ports:
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
      - name: 8778-tcp
        protocol: TCP
        port: 8778
        targetPort: 8778
    selector:
      app: quarkus-order-processor-ui
    type: ClusterIP
    sessionAffinity: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: quarkus-order-processor-ui
    labels:
      app: quarkus-order-processor-ui
  spec:
    to:
      kind: Service
      name: quarkus-order-processor-ui
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
parameters:
- description: Backend url
  name: BACKEND_URL
  value: 'http://quarkus-order-processor-api:8080'
- description: Container image to use
  name: IMAGE
  required: true
- description: Description of this deployment
  name: CAUSE
  required: true