apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: quarkus-datagrid-infra
message: This is a template to start infra components.
metadata:
  name: infra
  annotations:
    description: "quarkus-datagrid infra components"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: datagrid
    generation: 1
    labels:
      app: datagrid
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: datagrid
    template:
      metadata:
        labels:
          app: datagrid
      spec:
        containers:
          - name: datagrid
            image: quay.io/gmagnotta/datagrid:latest
            args: ["--cluster-stack=kubernetes", "-Djgroups.dns.query=datagridnodes", "-Dinfinispan.cluster.name=London"]
            ports:
              - containerPort: 11222
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
              - containerPort: 7800
                protocol: TCP
            resources:
              requests:
                cpu: "500m"
                memory: "128Mi"
              limits:
                cpu: "1000m"
                memory: "1024Mi"
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: datagrid
    labels:
      app: datagrid
  spec:
    ports:
      - name: 11222-tcp
        protocol: TCP
        port: 11222
        targetPort: 11222
      - name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
      - name: 8443-tcp
        protocol: TCP
        port: 8443
        targetPort: 8443
    selector:
      app: datagrid
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Service
  metadata:
    name: datagridnodes
    labels:
      app: datagridnodes
  spec:
    publishNotReadyAddresses: true
    clusterIP: None
    ports:
      - name: 7800-tcp
        protocol: TCP
        port: 7800
        targetPort: 7800
    selector:
      app: datagrid
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: datagrid
    labels:
      app: datagrid
  spec:
    to:
      kind: Service
      name: datagrid
      weight: 100
    port:
      targetPort: 11222-tcp
    wildcardPolicy: None
parameters:
