kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-from-hello-dev
subjects:
  - kind: User
    name: system:serviceaccount:hello-dev:pipeline
    namespace: hello-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit