apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: webapp-serverless
message: This is an OpenShift template to deploy webapp as serverless.
metadata:
  name: webapp-serverless
  annotations:
    description: "webapp Template"
objects:
- apiVersion: serving.knative.dev/v1
  kind: Service
  metadata:
    name: webapp-serverless
  spec:
    template:
      metadata:
        labels:
          app: webapp-serverless
        annotations:
          autoscaling.knative.dev/min-scale: "0"
          autoscaling.knative.dev/target: "1"
      spec:
        containerConcurrency: 0
        containers:
          - name: webapp
            image: ${IMAGE}
            ports:
              - containerPort: 8080
                protocol: TCP
parameters:
- description: Container image to use
  name: IMAGE
  required: true