//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.12 at 04:30:05 PM CEST 
//


package com.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Shiporder_QNAME = new QName("", "shiporder");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Shipordertype }
     * 
     */
    public Shipordertype createShipordertype() {
        return new Shipordertype();
    }

    /**
     * Create an instance of {@link Itemtype }
     * 
     */
    public Itemtype createItemtype() {
        return new Itemtype();
    }

    /**
     * Create an instance of {@link Shiptotype }
     * 
     */
    public Shiptotype createShiptotype() {
        return new Shiptotype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Shipordertype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shiporder")
    public JAXBElement<Shipordertype> createShiporder(Shipordertype value) {
        return new JAXBElement<Shipordertype>(_Shiporder_QNAME, Shipordertype.class, null, value);
    }

}
