apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: sqs-knative-adapter-containersource
message: This is an OpenShift template to deploy sqs-knative-adapter as a containersource.
metadata:
  name: sqs-knative-adapter-containersource
  annotations:
    description: "sqs-knative-adapter Template"
objects:
- apiVersion: sources.knative.dev/v1
  kind: ContainerSource
  metadata:
    name: sqs-knative-adapter
  spec:
    template:
      spec:
        containers:
          - name: sqs-knative-adapter
            image: ${IMAGE}
            env:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: sqs-knative-adapter
                    key: aws_access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: sqs-knative-adapter
                    key: aws_secret_access_key
              - name: SQS_QUEUE
                valueFrom:
                  secretKeyRef:
                    name: sqs-knative-adapter
                    key: sqs_queue
            ports:
              - containerPort: 8080
                protocol: TCP
    sink:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: default
parameters:
- description: Container image to use
  name: IMAGE
  required: true